version: '3.7'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/letsencrypt/
      - ./logs:/var/log/nginx/
    ports:
      - 80:80
      - 443:443
